apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  labels:
    f5cr: "true"
  name: chronograf-tls
  namespace: default
spec:
  hosts:
    - chronograf.mattconnley.com
  tls:
    clientSSL: tls-chronograf
    reference: secret
    termination: edge

---

apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: chronograf-virtual-server
  namespace: default
spec:
  host: chronograf.mattconnley.com
  httpTraffic: redirect
  pools:
  - path: /
    service: chronograf-chronograf
    servicePort: 8888
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 10
  tlsProfileName: chronograf-tls
  virtualServerAddress: 192.168.10.51
  virtualServerName: "chronograf-virtual-server"
