apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  labels:
    f5cr: "true"
  name: cribl-tls
  namespace: default
spec:
  hosts:
    - cribl.mattconnley.com
  tls:
    clientSSL: tls-cribl
    reference: secret
    termination: edge

---

apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: cribl-virtual-server
  namespace: default
spec:
  host: cribl.mattconnley.com
  httpTraffic: redirect
  pools:
  - path: /
    service: cribl-leader
    servicePort: 9000
    monitor:
      type: http
      send: "GET/r/n"
      recv: ""
      interval: 10
      timeout: 10
  tlsProfileName: cribl-tls
  virtualServerAddress: 192.168.10.56
  virtualServerName: "cribl-virtual-server"
