apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  labels:
    f5cr: "true"
  name: grafana-tls
  namespace: default
spec:
  hosts:
    - grafana.mattconnley.com
  tls:
    clientSSL: tls-grafana
    reference: secret
    termination: edge

---

apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: grafana-virtual-server-edge
  namespace: default
spec:
  host: grafana.mattconnley.com
  httpTraffic: redirect
  pools:
  - path: /
    service: grafana
    servicePort: 3000
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 10
  tlsProfileName: grafana-tls
  virtualServerAddress: 192.168.10.52
  virtualServerName: "grafana-virtual-server"
