apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: f5-transport-server-influxdb
  namespace: default
spec:
  mode: standard
  persistenceProfile: "destination-address"
  pool:
    loadBalancingMethod: fastest-node
    monitor:
      type: tcp
      interval: 10
      timeout: 10
    service: influxdb
    servicePort: 8086
  profiles:
    tcp:
      client: /Common/f5-tcp-lan
      server: /Common/f5-tcp-wan
  snat: auto
  virtualServerAddress: "192.168.10.50"
  virtualServerName: influxdb-transport-server-tcp
  virtualServerPort: 8086