apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  labels:
    f5cr: "true"
  name: nsupdateapi-tls
  namespace: default
spec:
  hosts:
    - nsupdateapi.mattconnley.com
  tls:
    clientSSL: tls-nsupdateapi
    reference: secret
    termination: edge

---

apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: nsupdateapi-virtual-server
  namespace: default
spec:
  host: nsupdateapi.mattconnley.com
  httpTraffic: redirect
  pools:
  - path: /
    service: nsupdateapi
    servicePort: 9000
    monitor:
      type: http
      send: "GET/r/n"
      recv: ""
      interval: 10
      timeout: 10
  tlsProfileName: nsupdateapi-tls
  virtualServerAddress: 192.168.10.58
  virtualServerName: "nsupdateapi-virtual-server"
