apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  labels:
    f5cr: "true"
  name: personalweb-tls
  namespace: default
spec:
  hosts:
    - personalweb.mattconnley.com
  tls:
    clientSSL: tls-personalweb
    reference: secret
    termination: edge

---

apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: personalweb-virtual-server
  namespace: default
spec:
  host: personalweb.mattconnley.com
  httpTraffic: redirect
  pools:
  - path: /
    service: personalweb
    servicePort: 9000
    monitor:
      type: http
      send: "GET/r/n"
      recv: ""
      interval: 10
      timeout: 10
  tlsProfileName: personalweb-tls
  virtualServerAddress: 192.168.10.80
  virtualServerName: "personalweb-virtual-server"
