apiVersion: cis.f5.com/v1
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: f5-transport-server-postgres
  namespace: default
spec:
  mode: standard
  persistenceProfile: destination-address
  pool:
    loadBalancingMethod: fastest-node
    monitor:
      interval: 10
      timeout: 10
      type: tcp
    service: postgres-postgresql
    servicePort: 5432
  profiles:
    tcp:
      client: /Common/f5-tcp-lan
      server: /Common/f5-tcp-wan
  snat: auto
  virtualServerAddress: 192.168.10.60
  virtualServerName: postgres-transport-server-tcp
  virtualServerPort: 5432